import { useEffect, useState, type FormEvent } from 'react'
import { api, certificatePdf } from '../services/api'
import type { CertificateTemplate } from '../types/certificate'

export function AdminCertificateTemplatesPage() {
  const [templates, setTemplates] = useState<CertificateTemplate[]>([])
  const [name, setName] = useState('Participation certificate')
  const [file, setFile] = useState<File | null>(null)
  const [error, setError] = useState(''); const [message, setMessage] = useState(''); const [busy, setBusy] = useState(false); const [reload, setReload] = useState(0)
  useEffect(() => { api.templates().then(setTemplates).catch(err => setError(err.message)) }, [reload])
  async function act(action: () => Promise<unknown>, success: string) { setBusy(true); setError(''); setMessage(''); try { await action(); setMessage(success); setReload(v => v + 1) } catch (err) { setError(err instanceof Error ? err.message : 'Action failed') } finally { setBusy(false) } }
  function upload(event: FormEvent) { event.preventDefault(); if (file) void act(() => api.uploadTemplate(name, file), 'Template uploaded. Activate it when ready.') }
  function edit(id: number, changes: Partial<CertificateTemplate>) { setTemplates(items => items.map(item => item.id === id ? { ...item, ...changes } : item)) }
  return <>
    <div className="admin-page-heading"><div><span className="eyebrow">/ CERTIFICATE SYSTEM</span><h1>TEMPLATES<span>.</span></h1><p>Configure only the participant name and college overlays; all other wording stays in the template.</p></div></div>
    {error && <div className="form-error" role="alert">{error}</div>}{message && <div className="form-success">{message}</div>}
    <form className="certificate-upload" onSubmit={upload}><label>TEMPLATE NAME<input required value={name} onChange={e => setName(e.target.value)} /></label><label>FILE<input required type="file" accept="image/png,image/jpeg,application/pdf" onChange={e => setFile(e.target.files?.[0] || null)} /></label><button className="button button-dark" disabled={busy || !file}>UPLOAD TEMPLATE →</button></form>
    <div className="certificate-list">{templates.map(template => <section className="certificate-card" key={template.id}>
      <div className="certificate-card-head"><strong>{template.name}</strong><span className={`status-pill ${template.is_active ? 'active' : 'inactive'}`}>{template.is_active ? 'ACTIVE' : 'INACTIVE'}</span><span>{template.file_type.toUpperCase()}</span></div>
      <div className="certificate-fields"><label>TEMPLATE NAME<input value={template.name} onChange={e => edit(template.id, { name: e.target.value })} /></label><label>NAME X %<input type="number" min="0" max="100" value={template.name_x} onChange={e => edit(template.id, { name_x: Number(e.target.value) })} /></label><label>NAME Y %<input type="number" min="0" max="100" value={template.name_y} onChange={e => edit(template.id, { name_y: Number(e.target.value) })} /></label><label>NAME SIZE<input type="number" min="8" max="200" value={template.name_font_size} onChange={e => edit(template.id, { name_font_size: Number(e.target.value) })} /></label><label>NAME ALIGN<select value={template.name_alignment} onChange={e => edit(template.id, { name_alignment: e.target.value as CertificateTemplate['name_alignment'] })}><option value="left">LEFT</option><option value="center">CENTER</option><option value="right">RIGHT</option></select></label><label>NAME COLOR<input type="color" value={template.name_color} onChange={e => edit(template.id, { name_color: e.target.value })} /></label><label>COLLEGE X %<input type="number" min="0" max="100" value={template.college_x} onChange={e => edit(template.id, { college_x: Number(e.target.value) })} /></label><label>COLLEGE Y %<input type="number" min="0" max="100" value={template.college_y} onChange={e => edit(template.id, { college_y: Number(e.target.value) })} /></label><label>COLLEGE SIZE<input type="number" min="8" max="200" value={template.college_font_size} onChange={e => edit(template.id, { college_font_size: Number(e.target.value) })} /></label><label>COLLEGE ALIGN<select value={template.college_alignment} onChange={e => edit(template.id, { college_alignment: e.target.value as CertificateTemplate['college_alignment'] })}><option value="left">LEFT</option><option value="center">CENTER</option><option value="right">RIGHT</option></select></label><label>COLLEGE COLOR<input type="color" value={template.college_color} onChange={e => edit(template.id, { college_color: e.target.value })} /></label></div>
      <p className="certificate-help">Preview uses ALEX JOHNSON and EXAMPLE COLLEGE.</p>
      <div className="certificate-actions"><button disabled={busy} onClick={() => void act(() => api.updateTemplate(template.id, template), 'Placement saved.')} type="button">SAVE PLACEMENT</button><button type="button" onClick={() => void certificatePdf(`/api/certificates/templates/${template.id}/preview`).catch(err => setError(err.message))}>PREVIEW PDF</button>{!template.is_active && <button type="button" onClick={() => void act(() => api.activateTemplate(template.id), 'Template activated.')}>ACTIVATE</button>}<label className="certificate-file-action">REPLACE FILE<input type="file" accept="image/png,image/jpeg,application/pdf" onChange={e => { const next = e.target.files?.[0]; if (next) void act(() => api.replaceTemplate(template.id, next), 'Template replaced.') }} /></label>{!template.is_active && <button type="button" onClick={() => void act(() => api.deleteTemplate(template.id), 'Template deleted.')}>DELETE</button>}</div>
    </section>)}</div>
  </>
}
